name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libgstreamer1.0-dev \
          libtool \
          libtool-bin \
          autoconf \
          automake \
          pkg-config

    - name: Install buildozer and dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install --upgrade Cython==0.29.33 virtualenv
        pip install --upgrade buildozer
        pip install --upgrade python-for-android

    - name: Initialize python-for-android
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        git clone --depth=1 https://github.com/kivy/python-for-android.git $HOME/.buildozer/android/platform/python-for-android
        cd $HOME/.buildozer/android/platform/python-for-android
        python setup.py install

    - name: Accept Android licenses
      run: |
        yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Clean and build APK
      run: |
        rm -rf .buildozer
        rm -rf bin
        buildozer android clean
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: trendingvideos-debug
        path: bin/*.apk
        compression-level: 0