name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zip \
            unzip \
            curl

      - name: Set up Android SDK and NDK
        run: |
          mkdir -p ~/.buildozer/android/platform/
          export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=~/.buildozer/android/platform/android-ndk-r25b
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          
          # Download and setup Android SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Accept licenses and install required packages
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "platforms;android-33" \
            "build-tools;33.0.0" \
            "platform-tools" \
            "ndk;25.2.9519653"
          
          # Create symlink for NDK
          ln -s $ANDROID_HOME/ndk/25.2.9519653 $ANDROID_NDK_HOME

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: trendingvideos-debug
          path: bin/*.apk
          if-no-files-found: error