name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Cache Buildozer dependencies
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('requirements.txt', 'buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config

      - name: Download Android SDK and NDK
        run: |
          mkdir -p ~/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d ~/.buildozer/android/platform/
          mv ~/.buildozer/android/platform/cmdline-tools ~/.buildozer/android/platform/latest
          mkdir -p ~/.buildozer/android/platform/cmdline-tools
          mv ~/.buildozer/android/platform/latest ~/.buildozer/android/platform/cmdline-tools/
          yes | ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653"
          echo "ANDROID_SDK_ROOT=~/.buildozer/android/platform" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=~/.buildozer/android/platform/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: trendingvideos-debug
          path: bin/*.apk
          if-no-files-found: error